database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: kris

  # the password
  password:

  # the JDBC URL
  url: jdbc:postgresql://127.0.0.1/strengths

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

#server:
#  applicationConnectors:
#    - type: http
#      port: 8080
#  adminConnectors:
#    - type: http
#      port: 8081

server:
  type: simple
  applicationContextPath: /
  rootPath: /api/*
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    com.krisrichardson.restume: DEBUG

  appenders:
    - type: console

swagger:
  resourcePackage: com.razrmarketing.strengths.resources